server:
  port: 9092
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/htatrip
    username: root
    password: rootdts123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
