server:
  port: 9191

spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id : vehicleservice
          uri : lb://vehicleservice
          predicates :
            - Path=/vehicle/**
        - id : authservice
          uri : lb://authservice
          predicates:
            - Path=/user/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http//localhost:9191/user/outh/checkToken


#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 4000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

jwt:
  secret: dtsangeeth
